### ISSUE TITLE
Only supports single-point prompts ?

### ISSUE THREAD

**Issue by onefish51** [frank-xwang/UnSAM#12]
This is truly outstanding work! I tested and compared UnSAM with SAM2 and found that your image segmentation is much more detailed! Amazing!

For Point-based promptable segmentation，I added two or more points, but the result only responded to one of them. Does this model only support single-point predictions?
![image](https://github.com/user-attachments/assets/f4a41bb2-aa98-4a7c-804a-2d0238e9107b)
output image:
![image](https://github.com/user-attachments/assets/cec59ce4-43c6-4bbd-ab52-a905f8727fd0)

What is the specific difference between whole-image segmentation and promptable image segmentation? 

As we know, SAM and Semantic-SAM achieve whole-image segmentation by uniformly sampling a set of point prompts across the entire image. How do you differ from them? 
![image](https://github.com/user-attachments/assets/00c72687-19cd-4d93-a545-803507711266)

I noticed there is a file named `UnSAM/promptable_segmentation/demo_auto_generation.py`. Is this used for comparative testing with Semantic-SAM? Is your network architecture similar to that of Semantic-SAM?

**Comment by frank-xwang** [comment]
Hi,  

Thank you for your question and great to hear that you found our method can provide more detailed results than SAM-2! 

For point-based promptable segmentation, our method is currently based on Semantic-SAM, so we don’t support the use of multiple points at this time. That said, we’re considering releasing an updated version of UnSAM with support for promptable segmentation using multiple points in the future.  

For whole-image segmentation, you can use our whole-image segmentation pipeline, which is built on Mask2Former. This approach is significantly faster than SAM or Semantic-SAM. 

Let me know if you have any further questions!
