### ISSUE TITLE
Colab with CUDA broken Pillow install

### ISSUE THREAD

**Issue by tteresi7** [frank-xwang/UnSAM#14]
Colab installs Pillow version 10.5.0 when uncommenting the GPU lines.  You need before 9.5.0 otherwise the following error occurs

`AttributeError: module 'PIL.Image' has no attribute 'LINEAR'` when performing imports

**Comment by tteresi7** [comment]
Actually it seems no matter what I do it's still referencing 10.5.0.  I've tried uninstalling it with pip, it can't find it, I've tried reseting run time.  No matter what it just keeps importing 10.5.0 somehow.  Maybe a google colab issue?

**Comment by frank-xwang** [comment]
Hi, sorry for the late reply. I have never met this issue. It seems to be the Google Colab issue. You may want to post an issue under https://github.com/googlecolab/colabtools/issues
