### ISSUE TITLE
divide_conquer not imported 

### ISSUE THREAD

**Issue by boumpteryx** [frank-xwang/UnSAM#2]
In the divide_conquer notebook, this error appears:
ModuleNotFoundError: No module named 'divide_conquer'

**Comment by frank-xwang** [comment]
Hello, did you run the notebook inside the UnSAM/divide_and_conquer folder? I just tried it locally and it worked fine for me.

**Comment by frank-xwang** [comment]
Hi, could you please try again? I've updated the Colab, and it should be working now. Thanks for bringing this issue to my attention! :-)

**Comment by frank-xwang** [comment]
Closing it for now. Please feel free to re-open it if you have more questions.
