### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by flashingtt** [frank-xwang/UnSAM#3]
Hi, is there any way to pre-trained model moby_swin_t_300ep_pretrained.pth?

**Comment by frank-xwang** [comment]
Hi, you can download the pretrained model from this link: https://drive.google.com/file/d/1PS1Q0tAnUfBWLRPxh9iUrinAxeq7Y--u/view

**Comment by frank-xwang** [comment]
closing it for now. please re-open it if you have more questions.
