### ISSUE TITLE
Request for Release of Training Code for UnSAM

### ISSUE THREAD

**Issue by zhixuanli** [frank-xwang/UnSAM#4]
Great work on UnSAM! Would you mind sharing the training code? 

It would really help us out in the community. Thanks a lot!

**Comment by zhixuanli** [comment]
I have found "train.sh" under the two task folders. 
Are they the correct commands to regenerate the performance on paper? Thank you!

**Comment by zhixuanli** [comment]
By the way, could you please tell me how many hours it will need to train 8 epochs with four A100 or eight 3090? Thanks!

**Comment by frank-xwang** [comment]
Hi, the training time depends on the training settings. if you want to pretrain the model on 1% of SA1B data, it may take about 2-3 days using 4 A100 GPUs.

**Comment by zhixuanli** [comment]
Thanks for your detailed response. They are very helpful. Thank you and have a nice day!

**Comment by HYH-M87** [comment]
@zhixuanli Hello, may I ask if you have successfully started the model training?

**Comment by zhixuanli** [comment]
Hi @HYH-M87 , I haven't started, still working on information collecting and idea preparation.

**Comment by baibizhe** [comment]
I would like to train test this method on a larger dataset, such as original SAM dataset , on a larger model to provide a better foundation model to community. Meanwhile, we could use some efficient-SAM architecture to speed up training efficiency. I have around 16 A100 and 30 H20  idling. Contact me at bizhe.bai@outlook.com

**Comment by frank-xwang** [comment]
@baibizhe That would be fantastic! Let me know if you need any support from my side! Looking forward to it!
