### ISSUE TITLE
what is the minimun VRAM require?

### ISSUE THREAD

**Issue by PoopBear1** [frank-xwang/UnSAM#6]
Hello there,

Thank you for this work. I am wondering what the minimum VRAM required for inference is. Since I have a single RTX 3090, while I am inferring a single image, I received an OOM error. May I ask for your suggested VRAM for inference or any other settings I can change in order to get a prediction?

Thank you.

**Comment by HYH-M87** [comment]
@PoopBear1 Hello, may I ask if you have resolved this issue? I have the same issue: GPU memory overflow during training (batchsize set to 1).

**Comment by frank-xwang** [comment]
Hello, for additional insights into virtual memory usage during inference, please refer to the discussion at https://github.com/frank-xwang/UnSAM/issues/7#issuecomment-2222167872.

During training, to minimize memory usage, you could consider training the model with fewer masks per image by reducing the `MASK_FORMER.NUM_OBJECT_QUERIES` setting. Alternatively, lowering the image resolution by adjusting `INPUT.IMAGE_SIZE` could also help manage memory demands.

Feel free to ask if you have further questions!
